client:
  mysql:
    host: localhost
    port: 3306
    db: nakaliving
    user: root
    pass: mydatabasepassword
  http:
    address: 0.0.0.0:3000
auth:
  session:
    secret: secret
    maxAge: 1296000 # 15 days in second unit