name: nakaliving
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./database/mysql:/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mydatabasepassword